server:
#  port: 9091
  port: ${port:9091}
jdbc: #数据库连接池（spring-boot有默认的数据库连接池）
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql:///study_db
  username: root
  password: zqy19970114
  initialSize: 5
  maxActive: 10
  maxWait: 3000

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为服务地址，
      # 如果是集群，指定其他集群地址，以逗号隔开
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    # 更倾向于使用ip地址，而不是host名
    prefer-ip-address: true
    # ip地址
    ip-address: 127.0.0.1
    # 续约间隔，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
